#include "HelpPage.hpp"
#include "../../../../../../../Qt/6.6.3/gcc_64/include/QtWidgets/QWidget"
#include "ui_HelpPage.h" // generated by uic from HelpPage.ui

#include <QListWidgetItem>
#include <iostream>
#include <ostream>

// ---------------------------------------------------------------------------
// Construction / destruction
// ---------------------------------------------------------------------------

HelpPage::HelpPage(QWidget *parent)
    : QDialog(parent)
    , ui(new Ui::HelpPage)
{
    std::cout << "HelpPage::HelpPage()" << std::endl;
    ui->setupUi(this);
    setWindowTitle(tr("Help — Traffic Generator"));

    // Start on the first section
    ui->navList->setCurrentRow(0);
    ui->contentStack->setCurrentIndex(0);

    setupConnections();
}

HelpPage::~HelpPage() {
    delete ui;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

void HelpPage::showSection(Section section) {
    int idx = static_cast<int>(section);
    if (idx >= 0 && idx < ui->navList->count()) {
        ui->navList->setCurrentRow(idx);
        ui->contentStack->setCurrentIndex(idx);
    }
    show();
    raise();
    activateWindow();
}

// ---------------------------------------------------------------------------
// Private helpers
// ---------------------------------------------------------------------------

void HelpPage::setupConnections() {
    // Navigation list → content stack
    connect(ui->navList, &QListWidget::itemClicked,
            this, &HelpPage::onNavItemClicked);

    // Also handle keyboard navigation (currentRowChanged)
    connect(ui->navList, &QListWidget::currentRowChanged,
            ui->contentStack, &QStackedWidget::setCurrentIndex);

    // Close button
    connect(ui->closeBtn, &QPushButton::clicked,
            this, &HelpPage::onCloseClicked);
}

// ---------------------------------------------------------------------------
// Private slots
// ---------------------------------------------------------------------------

void HelpPage::onNavItemClicked(QListWidgetItem *item) {
    int row = ui->navList->row(item);
    ui->contentStack->setCurrentIndex(row);
}

void HelpPage::onCloseClicked() {
    close();
}

void HelpPage::changeEvent(QEvent *event) {
    if (event->type() == QEvent::LanguageChange) {
        ui->retranslateUi(this);
    }
    QWidget::changeEvent(event);
}